### ISSUE TITLE
Subject schema

### ISSUE THREAD

**Issue by FearsomeRover** [kir-dev/ertekeloSCH#18]
Add the subject model to the prisma schema. Since subject rating already exists, you can also connect those two. See slack channel for the needed columns.

**Comment by EasySouls** [comment]
I already added the Subject schema in PR #17 
Of course it will be modified a little bit with the upcoming join tables, so I'll keep this issue open for now

**Comment by EasySouls** [comment]
In #26, the subject schema I think is done.
